# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLKitExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MLKitExample
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionLabelModel'
end
